### PR TITLE
Allow running app locally

### PR DESCRIPTION
**Pull request by glowacki-dev**
For development purpose use locally available firebase emulators
This makes development easier and allows running offline

Screenshot 2021-02-27 at 12 32 24

### CODE REVIEW

**Review by pastpatryk — APPROVED** [review]
Nice 👏

**Comment by pastpatryk** [comment]
The only problem I see is that we require `users` and `game_credentials` collections to exist in Firebase. Can you chack if we can configure the with this Firebase emulator, or we should create them on game start?

**Comment by glowacki-dev** [comment]
I initialize `users` collection with `DB.collection("users").doc("public_profiles").set({});` (is there a better way to do it?). `game_credentials` seem to get created automatically when first needed

**Comment by pastpatryk** [comment]
> I initialize `users` collection with `DB.collection("users").doc("public_profiles").set({});` (is there a better way to do it?). `game_credentials` seem to get created automatically when first needed

hmm.. 🤔 I '

**Pull request merged**
