### PR TITLE
Add Urban

### PR DESCRIPTION
**Pull request by turbaszek**

### CODE REVIEW

**Comment by kujbol** [comment]
czy to ten urban ? :D 
jerzy-urban-thumb-m

**Comment by morszczuk** [comment]
@kujbol Nope, this one:
image

**Comment by Bombasarkadian** [comment]
@turbaszek How about you resolve one of the issues related to phrases (#50, #51, #9) and add this one phrase as a small addition? 😃

**Comment by turbaszek** [comment]
@Bombasarkadian I will try to take a look over upcoming week

**Pull request closed without merging**
